global:
  # Scrape the targets for metrics every 15 seconds.
  scrape_interval: 15s
scrape_configs:
# Define our etcd cluster as a monitoring job.
- job_name: 'etcd'
  static_configs:
  - targets:
    - 127.0.0.1:2379

remote_write:
  - url: http://bridge:9091/receive
